/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-04-19 23:19:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ma.ac.esi.gameverseacademy.model.Mod;

public final class mods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Mod");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\"/>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("    <title>GameVerse Academy — Mods</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=DM+Sans:wght@300;400;500&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <style>\r\n");
      out.write("        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            --bg:          #0f0d17;\r\n");
      out.write("            --surface:     #1a1729;\r\n");
      out.write("            --surface2:    #201d30;\r\n");
      out.write("            --border:      rgba(167,139,250,.12);\r\n");
      out.write("            --border-hi:   rgba(167,139,250,.35);\r\n");
      out.write("            --lav:         #a78bfa;\r\n");
      out.write("            --lav-light:   #c4b5fd;\r\n");
      out.write("            --lav-dim:     #6d5ca8;\r\n");
      out.write("            --rose:        #f472b6;\r\n");
      out.write("            --teal:        #34d399;\r\n");
      out.write("            --text:        #ede9fe;\r\n");
      out.write("            --text-mid:    #9585c8;\r\n");
      out.write("            --text-lo:     #4a4068;\r\n");
      out.write("            --glow:        0 0 24px rgba(167,139,250,.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        html, body { min-height:100vh;background:var(--bg);color:var(--text);font-family:'DM Sans',sans-serif;overflow-x:hidden; }\r\n");
      out.write("\r\n");
      out.write("        /* ── AMBIENT ────────────────────────────────── */\r\n");
      out.write("        .orb { position:fixed;pointer-events:none;z-index:0;border-radius:50%;filter:blur(90px); }\r\n");
      out.write("        .orb-1 { width:600px;height:600px;top:-200px;left:-150px;\r\n");
      out.write("                 background:radial-gradient(circle,rgba(109,92,168,.22) 0%,transparent 70%);\r\n");
      out.write("                 animation:dA 18s ease-in-out infinite alternate; }\r\n");
      out.write("        .orb-2 { width:500px;height:500px;bottom:-100px;right:-100px;\r\n");
      out.write("                 background:radial-gradient(circle,rgba(167,139,250,.15) 0%,transparent 70%);\r\n");
      out.write("                 animation:dB 22s ease-in-out infinite alternate; }\r\n");
      out.write("        @keyframes dA { from{transform:translate(0,0)} to{transform:translate(40px,30px)} }\r\n");
      out.write("        @keyframes dB { from{transform:translate(0,0)} to{transform:translate(-30px,-40px)} }\r\n");
      out.write("        body::before {\r\n");
      out.write("            content:'';position:fixed;inset:0;z-index:0;pointer-events:none;\r\n");
      out.write("            background-image:radial-gradient(circle,rgba(167,139,250,.05) 1px,transparent 1px);\r\n");
      out.write("            background-size:32px 32px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── SIDEBAR ────────────────────────────────── */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            position:fixed;left:0;top:0;bottom:0;width:220px;\r\n");
      out.write("            background:rgba(13,11,21,.95);backdrop-filter:blur(20px);\r\n");
      out.write("            border-right:1px solid var(--border);\r\n");
      out.write("            display:flex;flex-direction:column;padding:2rem 0;z-index:100;\r\n");
      out.write("        }\r\n");
      out.write("        .s-logo { padding:0 1.6rem 1.8rem;border-bottom:1px solid var(--border);margin-bottom:1.5rem; }\r\n");
      out.write("        .s-logo .mark {\r\n");
      out.write("            font-family:'Cinzel',serif;font-size:1.05rem;font-weight:700;letter-spacing:.06em;\r\n");
      out.write("            background:linear-gradient(135deg,var(--lav-light),var(--lav));\r\n");
      out.write("            -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;line-height:1.25;\r\n");
      out.write("        }\r\n");
      out.write("        .s-logo .sub { font-size:.6rem;letter-spacing:.22em;text-transform:uppercase;color:var(--text-lo);margin-top:.3rem; }\r\n");
      out.write("        .nav-sec { padding:0 .8rem;flex:1; }\r\n");
      out.write("        .nav-lbl { font-size:.58rem;letter-spacing:.2em;text-transform:uppercase;color:var(--text-lo);padding:.4rem .8rem .7rem; }\r\n");
      out.write("        .nav-a {\r\n");
      out.write("            display:flex;align-items:center;gap:.75rem;padding:.65rem .8rem;border-radius:8px;\r\n");
      out.write("            text-decoration:none;color:var(--text-mid);font-size:.82rem;letter-spacing:.01em;\r\n");
      out.write("            transition:all .2s;margin-bottom:.12rem;position:relative;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-a svg { width:15px;height:15px;flex-shrink:0;opacity:.65; }\r\n");
      out.write("        .nav-a:hover { background:rgba(167,139,250,.08);color:var(--lav-light); }\r\n");
      out.write("        .nav-a:hover svg,.nav-a.active svg { opacity:1; }\r\n");
      out.write("        .nav-a.active { background:rgba(167,139,250,.14);color:var(--lav-light); }\r\n");
      out.write("        .nav-a.active::before {\r\n");
      out.write("            content:'';position:absolute;left:0;top:22%;bottom:22%;\r\n");
      out.write("            width:2px;background:var(--lav);border-radius:2px;box-shadow:var(--glow);\r\n");
      out.write("        }\r\n");
      out.write("        .s-foot { padding:1rem 1.6rem 0;border-top:1px solid var(--border);margin-top:auto; }\r\n");
      out.write("        .u-chip { display:flex;align-items:center;gap:.7rem; }\r\n");
      out.write("        .u-av {\r\n");
      out.write("            width:30px;height:30px;border-radius:50%;\r\n");
      out.write("            background:linear-gradient(135deg,var(--lav),var(--lav-dim));\r\n");
      out.write("            display:flex;align-items:center;justify-content:center;\r\n");
      out.write("            font-size:.62rem;font-weight:700;color:var(--bg);flex-shrink:0;box-shadow:var(--glow);\r\n");
      out.write("        }\r\n");
      out.write("        .u-name { font-size:.78rem;font-weight:500;color:var(--text); }\r\n");
      out.write("        .u-role { font-size:.62rem;color:var(--text-lo);letter-spacing:.04em; }\r\n");
      out.write("\r\n");
      out.write("        /* ── MAIN ───────────────────────────────────── */\r\n");
      out.write("        .main { margin-left:220px;position:relative;z-index:1;padding:2.5rem 2.5rem 4rem; }\r\n");
      out.write("\r\n");
      out.write("        /* ── PAGE HEADER ────────────────────────────── */\r\n");
      out.write("        .ph { display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:2rem; }\r\n");
      out.write("        .ph-left .ey {\r\n");
      out.write("            font-size:.62rem;letter-spacing:.25em;text-transform:uppercase;color:var(--lav);\r\n");
      out.write("            margin-bottom:.4rem;display:flex;align-items:center;gap:.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .ph-left .ey::before { content:'';display:inline-block;width:18px;height:1px;background:var(--lav);box-shadow:var(--glow); }\r\n");
      out.write("        .ph-left h1 {\r\n");
      out.write("            font-family:'Cinzel',serif;font-size:2.4rem;font-weight:700;letter-spacing:.04em;\r\n");
      out.write("            background:linear-gradient(135deg,#fff 0%,var(--lav-light) 55%,var(--lav) 100%);\r\n");
      out.write("            -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;line-height:1.1;\r\n");
      out.write("        }\r\n");
      out.write("        .ph-left .sub2 { font-size:.78rem;color:var(--text-lo);margin-top:.4rem;letter-spacing:.04em; }\r\n");
      out.write("        .btn-add {\r\n");
      out.write("            display:inline-flex;align-items:center;gap:.6rem;\r\n");
      out.write("            background:linear-gradient(135deg,var(--lav-dim),#4c3d8f);\r\n");
      out.write("            border:1px solid var(--lav);border-radius:10px;\r\n");
      out.write("            color:var(--lav-light);font-family:'Cinzel',serif;\r\n");
      out.write("            font-size:.75rem;font-weight:600;letter-spacing:.1em;\r\n");
      out.write("            padding:.75rem 1.5rem;cursor:pointer;text-decoration:none;text-transform:uppercase;\r\n");
      out.write("            box-shadow:var(--glow),inset 0 1px 0 rgba(255,255,255,.08);\r\n");
      out.write("            transition:all .25s;white-space:nowrap;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-add:hover { background:linear-gradient(135deg,#7c5cd6,#5a47a8);box-shadow:0 0 36px rgba(167,139,250,.45);transform:translateY(-2px); }\r\n");
      out.write("        .btn-add svg { width:14px;height:14px; }\r\n");
      out.write("\r\n");
      out.write("        /* ── CONTROLS ───────────────────────────────── */\r\n");
      out.write("        .ctrl { display:flex;align-items:center;gap:.75rem;margin-bottom:1.8rem;flex-wrap:wrap; }\r\n");
      out.write("        .srch { position:relative;flex:1;min-width:220px; }\r\n");
      out.write("        .srch svg { position:absolute;left:.9rem;top:50%;transform:translateY(-50%);width:14px;height:14px;stroke:var(--text-lo);pointer-events:none; }\r\n");
      out.write("        .srch input {\r\n");
      out.write("            width:100%;background:var(--surface);border:1px solid var(--border);border-radius:10px;\r\n");
      out.write("            color:var(--text);font-family:'DM Sans',sans-serif;font-size:.85rem;\r\n");
      out.write("            padding:.7rem 1rem .7rem 2.4rem;outline:none;transition:border-color .2s,box-shadow .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .srch input::placeholder { color:var(--text-lo); }\r\n");
      out.write("        .srch input:focus { border-color:var(--lav-dim);box-shadow:0 0 0 3px rgba(167,139,250,.12); }\r\n");
      out.write("        .pills { display:flex;gap:.5rem;flex-wrap:wrap; }\r\n");
      out.write("        .pill {\r\n");
      out.write("            padding:.45rem 1rem;border-radius:20px;border:1px solid var(--border);\r\n");
      out.write("            background:transparent;color:var(--text-mid);font-family:'DM Sans',sans-serif;\r\n");
      out.write("            font-size:.72rem;letter-spacing:.06em;text-transform:uppercase;cursor:pointer;transition:all .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .pill:hover { border-color:var(--lav-dim);color:var(--lav-light); }\r\n");
      out.write("        .pill.active { background:rgba(167,139,250,.15);border-color:var(--lav);color:var(--lav-light);box-shadow:0 0 12px rgba(167,139,250,.2); }\r\n");
      out.write("\r\n");
      out.write("        /* ── CARDS GRID ─────────────────────────────── */\r\n");
      out.write("        .cards-grid {\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:repeat(auto-fill,minmax(340px,1fr));\r\n");
      out.write("            gap:1.25rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .mod-card {\r\n");
      out.write("            background:var(--surface);border:1px solid var(--border);border-radius:14px;\r\n");
      out.write("    overflow:hidden;display:flex;flex-direction:column;align-items:stretch;\r\n");
      out.write("            transition:border-color .25s,box-shadow .25s,transform .2s;\r\n");
      out.write("            animation:fadeUp .5s ease both;position:relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mod-card::after {\r\n");
      out.write("            content:'';position:absolute;top:0;left:0;right:0;height:1px;\r\n");
      out.write("            background:linear-gradient(90deg,transparent,var(--lav),transparent);\r\n");
      out.write("            opacity:0;transition:opacity .3s;\r\n");
      out.write("        }\r\n");
      out.write("        .mod-card:hover { border-color:var(--border-hi);box-shadow:var(--glow);transform:translateY(-3px); }\r\n");
      out.write("        .mod-card:hover::after { opacity:1; }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeUp { from{opacity:0;transform:translateY(16px)} to{opacity:1;transform:translateY(0)} }\r\n");
      out.write("        .mod-card:nth-child(1){animation-delay:.05s}.mod-card:nth-child(2){animation-delay:.10s}\r\n");
      out.write("        .mod-card:nth-child(3){animation-delay:.15s}.mod-card:nth-child(4){animation-delay:.20s}\r\n");
      out.write("        .mod-card:nth-child(5){animation-delay:.25s}.mod-card:nth-child(6){animation-delay:.30s}\r\n");
      out.write("\r\n");
      out.write("        /* Image */\r\n");
      out.write("        .card-img {\r\n");
      out.write("           width:100%;min-width:unset;height:160px;background:var(--surface2);\r\n");
      out.write("    	overflow:hidden;flex-shrink:0;position:relative;\r\n");
      out.write("        }\r\n");
      out.write("        .card-img img { width:100%;height:100%;object-fit:cover;object-position:center top;display:block;transition:transform .4s ease; }\r\n");
      out.write("        .mod-card:hover .card-img img { transform:scale(1.08); }\r\n");
      out.write("        .id-badge {\r\n");
      out.write("            position:absolute;top:.5rem;left:.5rem;\r\n");
      out.write("            background:rgba(10,8,20,.75);backdrop-filter:blur(6px);\r\n");
      out.write("            border:1px solid var(--border);border-radius:5px;\r\n");
      out.write("            font-family:'Cinzel',serif;font-size:.58rem;color:var(--text-lo);padding:.15rem .4rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Body */\r\n");
      out.write("        .card-body { padding:1rem 1.1rem;display:flex;flex-direction:column;justify-content:space-between;flex:1;min-width:0; }\r\n");
      out.write("        .card-title { font-weight:500;font-size:.95rem;color:var(--text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-bottom:.4rem; }\r\n");
      out.write("\r\n");
      out.write("        /* Badge */\r\n");
      out.write("        .badge {\r\n");
      out.write("            display:inline-flex;align-items:center;gap:.3rem;\r\n");
      out.write("            font-size:.6rem;font-weight:500;letter-spacing:.1em;\r\n");
      out.write("            text-transform:uppercase;border-radius:20px;padding:.25rem .65rem;\r\n");
      out.write("        }\r\n");
      out.write("        .badge::before { content:'';width:5px;height:5px;border-radius:50%;flex-shrink:0; }\r\n");
      out.write("        .badge-Gameplay  { background:rgba(167,139,250,.12);color:var(--lav-light);border:1px solid rgba(167,139,250,.25); }\r\n");
      out.write("        .badge-Gameplay::before  { background:var(--lav);box-shadow:0 0 6px var(--lav); }\r\n");
      out.write("        .badge-Graphisme { background:rgba(244,114,182,.1);color:#f9a8d4;border:1px solid rgba(244,114,182,.22); }\r\n");
      out.write("        .badge-Graphisme::before { background:var(--rose);box-shadow:0 0 6px var(--rose); }\r\n");
      out.write("        .badge-Contenu   { background:rgba(52,211,153,.1);color:#6ee7b7;border:1px solid rgba(52,211,153,.2); }\r\n");
      out.write("        .badge-Contenu::before   { background:var(--teal);box-shadow:0 0 6px var(--teal); }\r\n");
      out.write("        .badge-default   { background:rgba(255,255,255,.05);color:var(--text-mid);border:1px solid var(--border); }\r\n");
      out.write("        .badge-default::before { background:var(--text-lo); }\r\n");
      out.write("\r\n");
      out.write("        /* Author */\r\n");
      out.write("        .card-author { display:flex;align-items:center;gap:.45rem;font-size:.78rem;color:var(--text-mid);margin-top:.5rem; }\r\n");
      out.write("        .author-av {\r\n");
      out.write("            width:20px;height:20px;border-radius:50%;\r\n");
      out.write("            background:linear-gradient(135deg,var(--lav),var(--lav-dim));\r\n");
      out.write("            display:flex;align-items:center;justify-content:center;\r\n");
      out.write("            font-size:.52rem;font-weight:700;color:var(--bg);flex-shrink:0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Downloads */\r\n");
      out.write("        .card-dl { margin-top:.7rem; }\r\n");
      out.write("        .dl-row { display:flex;justify-content:space-between;align-items:baseline;margin-bottom:.3rem; }\r\n");
      out.write("        .dl-num { font-family:'Cinzel',serif;font-size:.8rem;font-weight:600;color:var(--text); }\r\n");
      out.write("        .dl-lbl { font-size:.6rem;color:var(--text-lo);letter-spacing:.06em;text-transform:uppercase; }\r\n");
      out.write("        .dl-track { height:3px;background:rgba(255,255,255,.06);border-radius:3px;overflow:hidden; }\r\n");
      out.write("        .dl-fill { height:100%;border-radius:3px;transition:width .8s cubic-bezier(.4,0,.2,1); }\r\n");
      out.write("        .fill-lav  { background:linear-gradient(90deg,var(--lav-dim),var(--lav-light)); }\r\n");
      out.write("        .fill-rose { background:linear-gradient(90deg,#be185d,var(--rose)); }\r\n");
      out.write("        .fill-teal { background:linear-gradient(90deg,#059669,var(--teal)); }\r\n");
      out.write("\r\n");
      out.write("        /* Actions */\r\n");
      out.write("        .card-actions {\r\n");
      out.write("            display:flex;gap:.4rem;margin-top:.8rem;padding-top:.75rem;border-top:1px solid var(--border);\r\n");
      out.write("        }\r\n");
      out.write("        .ibtn {\r\n");
      out.write("            flex:1;display:flex;align-items:center;justify-content:center;gap:.4rem;\r\n");
      out.write("            padding:.45rem;border-radius:7px;border:1px solid var(--border);\r\n");
      out.write("            background:transparent;text-decoration:none;\r\n");
      out.write("            font-family:'DM Sans',sans-serif;font-size:.7rem;letter-spacing:.06em;text-transform:uppercase;\r\n");
      out.write("            cursor:pointer;transition:all .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .ibtn svg { width:12px;height:12px; }\r\n");
      out.write("        .ibtn.ed { color:var(--lav); } .ibtn.ed svg { stroke:var(--lav); }\r\n");
      out.write("        .ibtn.ed:hover { background:rgba(167,139,250,.12);border-color:var(--lav);box-shadow:var(--glow); }\r\n");
      out.write("        .ibtn.dl { color:#f4a0a0; } .ibtn.dl svg { stroke:#f4a0a0; }\r\n");
      out.write("        .ibtn.dl:hover { background:rgba(244,114,182,.1);border-color:var(--rose);box-shadow:0 0 20px rgba(244,114,182,.28); }\r\n");
      out.write("\r\n");
      out.write("        /* Empty state */\r\n");
      out.write("        .empty { text-align:center;padding:5rem 2rem;color:var(--text-lo);grid-column:1/-1; }\r\n");
      out.write("        .empty svg { width:48px;height:48px;stroke:var(--text-lo);margin-bottom:1rem;opacity:.4;display:block;margin-left:auto;margin-right:auto; }\r\n");
      out.write("        .empty p { font-size:.9rem;letter-spacing:.06em; }\r\n");
      out.write("\r\n");
      out.write("        /* Footer */\r\n");
      out.write("        .bar {\r\n");
      out.write("            margin-top:2rem;display:flex;align-items:center;justify-content:space-between;\r\n");
      out.write("            padding-top:1rem;border-top:1px solid var(--border);\r\n");
      out.write("        }\r\n");
      out.write("        .bar span { font-size:.68rem;letter-spacing:.1em;text-transform:uppercase;color:var(--text-lo); }\r\n");
      out.write("        .live { display:inline-flex;align-items:center;gap:.4rem; }\r\n");
      out.write("        .live::before { content:'';width:6px;height:6px;border-radius:50%;background:var(--teal);box-shadow:0 0 8px var(--teal);animation:pl 2s infinite; }\r\n");
      out.write("        @keyframes pl { 0%,100%{opacity:1}50%{opacity:.3} }\r\n");
      out.write("		.logout-btn {\r\n");
      out.write("    width:100%;display:flex;align-items:center;gap:.5rem;justify-content:center;\r\n");
      out.write("    padding:.5rem .8rem;border-radius:8px;border:1px solid var(--border);\r\n");
      out.write("    background:transparent;color:var(--text-mid);font-family:'DM Sans',sans-serif;\r\n");
      out.write("    font-size:.72rem;letter-spacing:.06em;text-transform:uppercase;\r\n");
      out.write("    cursor:pointer;transition:all .2s;\r\n");
      out.write("}\r\n");
      out.write(".logout-btn:hover {\r\n");
      out.write("    background:rgba(244,114,182,.08);border-color:var(--rose);\r\n");
      out.write("    color:#f9a8d4;box-shadow:0 0 14px rgba(244,114,182,.2);\r\n");
      out.write("}\r\n");
      out.write("        @media(max-width:900px){\r\n");
      out.write("            .sidebar{display:none}.main{margin-left:0;padding:1.5rem 1rem 3rem}\r\n");
      out.write("            .cards-grid{grid-template-columns:1fr}.card-img{width:90px;min-width:90px}\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"orb orb-1\"></div>\r\n");
      out.write("<div class=\"orb orb-2\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- SIDEBAR -->\r\n");
      out.write("<aside class=\"sidebar\">\r\n");
      out.write("    <div class=\"s-logo\">\r\n");
      out.write("        <div class=\"mark\">GameVerse<br>Academy</div>\r\n");
      out.write("        <div class=\"sub\">Admin Panel</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"nav-sec\">\r\n");
      out.write("        <div class=\"nav-lbl\">Navigation</div>\r\n");
      out.write("        <a href=\"home.jsp\" class=\"nav-a\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"/><polyline points=\"9 22 9 12 15 12 15 22\"/></svg>Accueil\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/games\" class=\"nav-a\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\"/><line x1=\"8\" y1=\"21\" x2=\"16\" y2=\"21\"/><line x1=\"12\" y1=\"17\" x2=\"12\" y2=\"21\"/></svg>Jeux\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"mods.jsp\" class=\"nav-a active\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z\"/></svg>Mods\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"utilisateurs.jsp\" class=\"nav-a\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/></svg>Utilisateurs\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"nav-lbl\" style=\"margin-top:1rem\">Compte</div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"s-foot\">\r\n");
      out.write("    <div class=\"u-chip\">\r\n");
      out.write("        <div class=\"u-av\">\r\n");
      out.write("            ");

                String sessionUser = (String) session.getAttribute("email");
                String av = (sessionUser != null && sessionUser.length() >= 2)
                    ? sessionUser.substring(0,2).toUpperCase()
                    : (sessionUser != null ? sessionUser.toUpperCase() : "?");
            
      out.write("\r\n");
      out.write("            ");
      out.print( av );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"u-name\">");
      out.print( sessionUser != null ? sessionUser : "Visiteur" );
      out.write("</div>\r\n");
      out.write("            <div class=\"u-role\">Super Admin</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" method=\"post\" style=\"margin-top:.75rem;\">\r\n");
      out.write("        <button type=\"submit\" class=\"logout-btn\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"\r\n");
      out.write("                 style=\"width:13px;height:13px;\">\r\n");
      out.write("                <path d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\"/>\r\n");
      out.write("                <polyline points=\"16 17 21 12 16 7\"/>\r\n");
      out.write("                <line x1=\"21\" y1=\"12\" x2=\"9\" y2=\"12\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            Déconnexion\r\n");
      out.write("        </button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<!-- MAIN -->\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"ph\">\r\n");
      out.write("        <div class=\"ph-left\">\r\n");
      out.write("            <div class=\"ey\">GameVerse Academy</div>\r\n");
      out.write("            <h1>Bibliothèque Mods</h1>\r\n");
      out.write("            <p class=\"sub2\">Gestion et supervision des modifications de </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/submitMod\" class=\"btn-add\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><line x1=\"12\" y1=\"5\" x2=\"12\" y2=\"19\"/><line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"/></svg>\r\n");
      out.write("            Ajouter un mod\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"ctrl\">\r\n");
      out.write("        <div class=\"srch\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"11\" cy=\"11\" r=\"8\"/><line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"/></svg>\r\n");
      out.write("            <input type=\"text\" id=\"searchInput\" placeholder=\"Rechercher par titre, auteur…\" oninput=\"filterCards()\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pills\">\r\n");
      out.write("            <button class=\"pill active\" onclick=\"setFilter('all',this)\">Tous</button>\r\n");
      out.write("            <button class=\"pill\" onclick=\"setFilter('Gameplay',this)\">Gameplay</button>\r\n");
      out.write("            <button class=\"pill\" onclick=\"setFilter('Graphisme',this)\">Graphisme</button>\r\n");
      out.write("            <button class=\"pill\" onclick=\"setFilter('Contenu',this)\">Contenu</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cards-grid\" id=\"grid\">\r\n");

    List<Mod> mods = (List<Mod>) request.getAttribute("mods");
    int MAX_DL = 100000;

    java.util.Map<String,String> imgMap = new java.util.HashMap<>();
    imgMap.put("dark souls", "https://cdn.akamai.steamstatic.com/steam/apps/570940/capsule_231x87.jpg");
    imgMap.put("skyrim",     "https://cdn.akamai.steamstatic.com/steam/apps/489830/capsule_231x87.jpg");
    imgMap.put("minecraft",  "https://cdn.akamai.steamstatic.com/steam/apps/1672970/capsule_231x87.jpg");
    imgMap.put("gta",        "https://cdn.akamai.steamstatic.com/steam/apps/271590/capsule_231x87.jpg");
    imgMap.put("cyberpunk",  "https://cdn.akamai.steamstatic.com/steam/apps/1091500/capsule_231x87.jpg");

    java.util.Map<String,String> fillMap = new java.util.HashMap<>();
    fillMap.put("Gameplay",  "fill-lav");
    fillMap.put("Graphisme", "fill-rose");
    fillMap.put("Contenu",   "fill-teal");

    if (mods != null && !mods.isEmpty()) {
        int idx = 0;
        for (Mod mod : mods) {
            idx++;
            String title     = mod.getTitle()    != null ? mod.getTitle()    : "";
            String category  = mod.getCategory() != null ? mod.getCategory() : "";
            String author    = mod.getAuthor()   != null ? mod.getAuthor()   : "";
            int    downloads = mod.getDownloads();
            int    pct       = Math.min(downloads * 100 / MAX_DL, 100);

            String imgSrc = "https://placehold.co/110x130/1a1729/a78bfa?text=MOD";
            String tl = title.toLowerCase();
            for (java.util.Map.Entry<String,String> e : imgMap.entrySet()) {
                if (tl.contains(e.getKey())) { imgSrc = e.getValue(); break; }
            }

            String badgeClass = fillMap.containsKey(category) ? "badge-" + category : "badge-default";
            String fillClass  = fillMap.getOrDefault(category, "fill-lav");
            String initials   = author.length() >= 2 ? author.substring(0,2).toUpperCase() : author.toUpperCase();

      out.write("\r\n");
      out.write("        <div class=\"mod-card\" data-category=\"");
      out.print( category );
      out.write("\">\r\n");
      out.write("            <div class=\"card-img\">\r\n");
      out.write("                <img src=\"");
      out.print( imgSrc );
      out.write("\" alt=\"");
      out.print( title );
      out.write("\"\r\n");
      out.write("                     onerror=\"this.src='https://placehold.co/110x130/1a1729/a78bfa?text=MOD'\"/>\r\n");
      out.write("                <div class=\"id-badge\">#");
      out.print( String.format("%02d", mod.getId()) );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"card-title\">");
      out.print( title );
      out.write("</div>\r\n");
      out.write("                    <span class=\"badge ");
      out.print( badgeClass );
      out.write('"');
      out.write('>');
      out.print( category.isEmpty() ? "—" : category );
      out.write("</span>\r\n");
      out.write("                    <div class=\"card-author\">\r\n");
      out.write("                        <div class=\"author-av\">");
      out.print( initials );
      out.write("</div>\r\n");
      out.write("                        ");
      out.print( author );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-dl\">\r\n");
      out.write("                        <div class=\"dl-row\">\r\n");
      out.write("                            <span class=\"dl-num\">");
      out.print( String.format("%,d", downloads).replace(',', ' ') );
      out.write("</span>\r\n");
      out.write("                            <span class=\"dl-lbl\">téléchargements</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dl-track\">\r\n");
      out.write("                            <div class=\"dl-fill ");
      out.print( fillClass );
      out.write("\" style=\"width:0\" data-pct=\"");
      out.print( pct );
      out.write("\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-actions\">\r\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/updateMod?id=");
      out.print( mod.getId() );
      out.write("\" class=\"ibtn ed\">\r\n");
      out.write("                        Modifier\r\n");
      out.write("                    </a>\r\n");
      out.write("				    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/deleteMod?id=");
      out.print( mod.getId() );
      out.write("\" class=\"ibtn dl\">\r\n");
      out.write("				    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("				        <polyline points=\"3 6 5 6 21 6\"/>\r\n");
      out.write("				        <path d=\"M19 6l-1 14H6L5 6\"/>\r\n");
      out.write("				        <path d=\"M10 11v6M14 11v6\"/>\r\n");
      out.write("				        <path d=\"M9 6V4h6v2\"/>\r\n");
      out.write("				    </svg>\r\n");
      out.write("				    Supprimer\r\n");
      out.write("				</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");

        }
    } else {

      out.write("\r\n");
      out.write("        <div class=\"empty\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\"><path d=\"M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z\"/></svg>\r\n");
      out.write("            <p>Aucun mod trouvé.</p>\r\n");
      out.write("        </div>\r\n");

    }

      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"bar\">\r\n");
      out.write("        <span class=\"live\" id=\"countLabel\"></span>\r\n");
      out.write("        <span>GameVerse Academy — Admin Panel</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.querySelectorAll('.dl-fill').forEach(el => {\r\n");
      out.write("        const pct = parseInt(el.dataset.pct) || 0;\r\n");
      out.write("        setTimeout(() => el.style.width = pct + '%', 400);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function updateCount() {\r\n");
      out.write("        const cards = [...document.querySelectorAll('#grid .mod-card')];\r\n");
      out.write("        const n = cards.filter(c => c.style.display !== 'none').length;\r\n");
      out.write("        document.getElementById('countLabel').textContent =\r\n");
      out.write("            n + ' mod' + (n > 1 ? 's' : '') + ' affiché' + (n > 1 ? 's' : '');\r\n");
      out.write("    }\r\n");
      out.write("    updateCount();\r\n");
      out.write("\r\n");
      out.write("    let af = 'all';\r\n");
      out.write("    function filterCards() {\r\n");
      out.write("        const q = document.getElementById('searchInput').value.toLowerCase();\r\n");
      out.write("        document.querySelectorAll('#grid .mod-card').forEach(card => {\r\n");
      out.write("            const ok = (af === 'all' || card.dataset.category === af) && card.textContent.toLowerCase().includes(q);\r\n");
      out.write("            card.style.display = ok ? '' : 'none';\r\n");
      out.write("        });\r\n");
      out.write("        updateCount();\r\n");
      out.write("    }\r\n");
      out.write("    function setFilter(cat, btn) {\r\n");
      out.write("        af = cat;\r\n");
      out.write("        document.querySelectorAll('.pill').forEach(b => b.classList.remove('active'));\r\n");
      out.write("        btn.classList.add('active');\r\n");
      out.write("        filterCards();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
