/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-04-19 21:26:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import ma.ac.esi.gameverseacademy.model.Mod;

public final class updateMod_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Mod");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Mod mod = (Mod) request.getAttribute("mod");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\"/>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("    <title>GameVerse Academy — Modifier un Mod</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=DM+Sans:wght@300;400;500&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <style>\r\n");
      out.write("        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            --bg:        #0f0d17;\r\n");
      out.write("            --surface:   #1a1729;\r\n");
      out.write("            --surface2:  #201d30;\r\n");
      out.write("            --border:    rgba(167,139,250,.12);\r\n");
      out.write("            --border-hi: rgba(167,139,250,.35);\r\n");
      out.write("            --lav:       #a78bfa;\r\n");
      out.write("            --lav-light: #c4b5fd;\r\n");
      out.write("            --lav-dim:   #6d5ca8;\r\n");
      out.write("            --rose:      #f472b6;\r\n");
      out.write("            --teal:      #34d399;\r\n");
      out.write("            --text:      #ede9fe;\r\n");
      out.write("            --text-mid:  #9585c8;\r\n");
      out.write("            --text-lo:   #4a4068;\r\n");
      out.write("            --glow:      0 0 24px rgba(167,139,250,.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        html, body { min-height:100vh; background:var(--bg); color:var(--text); font-family:'DM Sans',sans-serif; overflow-x:hidden; }\r\n");
      out.write("\r\n");
      out.write("        .orb { position:fixed; pointer-events:none; z-index:0; border-radius:50%; filter:blur(90px); }\r\n");
      out.write("        .orb-1 { width:600px; height:600px; top:-200px; left:-150px;\r\n");
      out.write("                 background:radial-gradient(circle,rgba(109,92,168,.22) 0%,transparent 70%);\r\n");
      out.write("                 animation:dA 18s ease-in-out infinite alternate; }\r\n");
      out.write("        .orb-2 { width:500px; height:500px; bottom:-100px; right:-100px;\r\n");
      out.write("                 background:radial-gradient(circle,rgba(167,139,250,.15) 0%,transparent 70%);\r\n");
      out.write("                 animation:dB 22s ease-in-out infinite alternate; }\r\n");
      out.write("        @keyframes dA { from{transform:translate(0,0)} to{transform:translate(40px,30px)} }\r\n");
      out.write("        @keyframes dB { from{transform:translate(0,0)} to{transform:translate(-30px,-40px)} }\r\n");
      out.write("        body::before {\r\n");
      out.write("            content:''; position:fixed; inset:0; z-index:0; pointer-events:none;\r\n");
      out.write("            background-image:radial-gradient(circle,rgba(167,139,250,.05) 1px,transparent 1px);\r\n");
      out.write("            background-size:32px 32px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* SIDEBAR */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            position:fixed; left:0; top:0; bottom:0; width:220px;\r\n");
      out.write("            background:rgba(13,11,21,.95); backdrop-filter:blur(20px);\r\n");
      out.write("            border-right:1px solid var(--border);\r\n");
      out.write("            display:flex; flex-direction:column; padding:2rem 0; z-index:100;\r\n");
      out.write("        }\r\n");
      out.write("        .s-logo { padding:0 1.6rem 1.8rem; border-bottom:1px solid var(--border); margin-bottom:1.5rem; }\r\n");
      out.write("        .s-logo .mark {\r\n");
      out.write("            font-family:'Cinzel',serif; font-size:1.05rem; font-weight:700; letter-spacing:.06em;\r\n");
      out.write("            background:linear-gradient(135deg,var(--lav-light),var(--lav));\r\n");
      out.write("            -webkit-background-clip:text; -webkit-text-fill-color:transparent; background-clip:text; line-height:1.25;\r\n");
      out.write("        }\r\n");
      out.write("        .s-logo .sub { font-size:.6rem; letter-spacing:.22em; text-transform:uppercase; color:var(--text-lo); margin-top:.3rem; }\r\n");
      out.write("        .nav-sec { padding:0 .8rem; flex:1; }\r\n");
      out.write("        .nav-lbl { font-size:.58rem; letter-spacing:.2em; text-transform:uppercase; color:var(--text-lo); padding:.4rem .8rem .7rem; }\r\n");
      out.write("        .nav-a {\r\n");
      out.write("            display:flex; align-items:center; gap:.75rem; padding:.65rem .8rem; border-radius:8px;\r\n");
      out.write("            text-decoration:none; color:var(--text-mid); font-size:.82rem; transition:all .2s; margin-bottom:.12rem; position:relative;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-a svg { width:15px; height:15px; flex-shrink:0; opacity:.65; }\r\n");
      out.write("        .nav-a:hover { background:rgba(167,139,250,.08); color:var(--lav-light); }\r\n");
      out.write("        .nav-a:hover svg { opacity:1; }\r\n");
      out.write("        .nav-a.active { background:rgba(167,139,250,.14); color:var(--lav-light); }\r\n");
      out.write("        .nav-a.active::before {\r\n");
      out.write("            content:''; position:absolute; left:0; top:22%; bottom:22%;\r\n");
      out.write("            width:2px; background:var(--lav); border-radius:2px; box-shadow:var(--glow);\r\n");
      out.write("        }\r\n");
      out.write("        .s-foot { padding:1rem 1.6rem 0; border-top:1px solid var(--border); margin-top:auto; }\r\n");
      out.write("        .u-chip { display:flex; align-items:center; gap:.7rem; }\r\n");
      out.write("        .u-av {\r\n");
      out.write("            width:30px; height:30px; border-radius:50%;\r\n");
      out.write("            background:linear-gradient(135deg,var(--lav),var(--lav-dim));\r\n");
      out.write("            display:flex; align-items:center; justify-content:center;\r\n");
      out.write("            font-size:.62rem; font-weight:700; color:var(--bg); flex-shrink:0; box-shadow:var(--glow);\r\n");
      out.write("        }\r\n");
      out.write("        .u-name { font-size:.78rem; font-weight:500; color:var(--text); }\r\n");
      out.write("        .u-role { font-size:.62rem; color:var(--text-lo); letter-spacing:.04em; }\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            width:100%; display:flex; align-items:center; gap:.5rem; justify-content:center;\r\n");
      out.write("            padding:.5rem .8rem; border-radius:8px; border:1px solid var(--border);\r\n");
      out.write("            background:transparent; color:var(--text-mid); font-family:'DM Sans',sans-serif;\r\n");
      out.write("            font-size:.72rem; letter-spacing:.06em; text-transform:uppercase;\r\n");
      out.write("            cursor:pointer; transition:all .2s; margin-top:.75rem;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn:hover { background:rgba(244,114,182,.08); border-color:var(--rose); color:#f9a8d4; }\r\n");
      out.write("\r\n");
      out.write("        /* MAIN */\r\n");
      out.write("        .main { margin-left:220px; position:relative; z-index:1; padding:2.5rem 2.5rem 4rem; }\r\n");
      out.write("\r\n");
      out.write("        /* PAGE HEADER */\r\n");
      out.write("        .ph { margin-bottom:2rem; }\r\n");
      out.write("        .ph .ey {\r\n");
      out.write("            font-size:.62rem; letter-spacing:.25em; text-transform:uppercase; color:var(--lav);\r\n");
      out.write("            margin-bottom:.4rem; display:flex; align-items:center; gap:.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .ph .ey::before { content:''; display:inline-block; width:18px; height:1px; background:var(--lav); }\r\n");
      out.write("        .ph h1 {\r\n");
      out.write("            font-family:'Cinzel',serif; font-size:2rem; font-weight:700; letter-spacing:.04em;\r\n");
      out.write("            background:linear-gradient(135deg,#fff 0%,var(--lav-light) 55%,var(--lav) 100%);\r\n");
      out.write("            -webkit-background-clip:text; -webkit-text-fill-color:transparent; background-clip:text; line-height:1.1;\r\n");
      out.write("        }\r\n");
      out.write("        .ph .sub2 { font-size:.78rem; color:var(--text-lo); margin-top:.4rem; }\r\n");
      out.write("\r\n");
      out.write("        /* FORM CARD */\r\n");
      out.write("        .form-card {\r\n");
      out.write("            background:var(--surface); border:1px solid var(--border); border-radius:16px;\r\n");
      out.write("            padding:2rem; max-width:680px; position:relative; overflow:hidden;\r\n");
      out.write("            animation:fadeUp .5s ease both;\r\n");
      out.write("        }\r\n");
      out.write("        .form-card::before {\r\n");
      out.write("            content:''; position:absolute; top:0; left:0; right:0; height:1px;\r\n");
      out.write("            background:linear-gradient(90deg,transparent,var(--lav),transparent);\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes fadeUp { from{opacity:0;transform:translateY(16px)} to{opacity:1;transform:translateY(0)} }\r\n");
      out.write("\r\n");
      out.write("        /* FORM FIELDS */\r\n");
      out.write("        .form-group { margin-bottom:1.4rem; }\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display:block; font-size:.72rem; letter-spacing:.12em; text-transform:uppercase;\r\n");
      out.write("            color:var(--text-mid); margin-bottom:.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group input,\r\n");
      out.write("        .form-group select,\r\n");
      out.write("        .form-group textarea {\r\n");
      out.write("            width:100%; background:var(--surface2); border:1px solid var(--border);\r\n");
      out.write("            border-radius:10px; color:var(--text); font-family:'DM Sans',sans-serif;\r\n");
      out.write("            font-size:.88rem; padding:.75rem 1rem; outline:none;\r\n");
      out.write("            transition:border-color .2s, box-shadow .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group input:focus,\r\n");
      out.write("        .form-group select:focus,\r\n");
      out.write("        .form-group textarea:focus {\r\n");
      out.write("            border-color:var(--lav-dim); box-shadow:0 0 0 3px rgba(167,139,250,.12);\r\n");
      out.write("        }\r\n");
      out.write("        .form-group textarea { resize:vertical; min-height:110px; }\r\n");
      out.write("        .form-group select option { background:var(--surface2); }\r\n");
      out.write("\r\n");
      out.write("        /* ID BADGE */\r\n");
      out.write("        .id-row {\r\n");
      out.write("            display:flex; align-items:center; gap:.6rem;\r\n");
      out.write("            margin-bottom:1.6rem; padding-bottom:1.2rem; border-bottom:1px solid var(--border);\r\n");
      out.write("        }\r\n");
      out.write("        .id-badge {\r\n");
      out.write("            font-family:'Cinzel',serif; font-size:.75rem; color:var(--lav);\r\n");
      out.write("            background:rgba(167,139,250,.1); border:1px solid rgba(167,139,250,.25);\r\n");
      out.write("            border-radius:6px; padding:.3rem .7rem;\r\n");
      out.write("        }\r\n");
      out.write("        .id-label { font-size:.72rem; color:var(--text-lo); letter-spacing:.1em; text-transform:uppercase; }\r\n");
      out.write("\r\n");
      out.write("        /* ACTIONS */\r\n");
      out.write("        .form-actions { display:flex; gap:.75rem; margin-top:1.8rem; padding-top:1.4rem; border-top:1px solid var(--border); }\r\n");
      out.write("        .btn-save {\r\n");
      out.write("            flex:1; display:flex; align-items:center; justify-content:center; gap:.6rem;\r\n");
      out.write("            background:linear-gradient(135deg,var(--lav-dim),#4c3d8f);\r\n");
      out.write("            border:1px solid var(--lav); border-radius:10px;\r\n");
      out.write("            color:var(--lav-light); font-family:'Cinzel',serif;\r\n");
      out.write("            font-size:.75rem; font-weight:600; letter-spacing:.1em; text-transform:uppercase;\r\n");
      out.write("            padding:.75rem 1.5rem; cursor:pointer;\r\n");
      out.write("            box-shadow:var(--glow), inset 0 1px 0 rgba(255,255,255,.08);\r\n");
      out.write("            transition:all .25s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-save:hover { background:linear-gradient(135deg,#7c5cd6,#5a47a8); transform:translateY(-2px); }\r\n");
      out.write("        .btn-cancel {\r\n");
      out.write("            display:flex; align-items:center; justify-content:center; gap:.6rem;\r\n");
      out.write("            padding:.75rem 1.5rem; border-radius:10px; border:1px solid var(--border);\r\n");
      out.write("            background:transparent; color:var(--text-mid); font-family:'DM Sans',sans-serif;\r\n");
      out.write("            font-size:.75rem; letter-spacing:.08em; text-transform:uppercase;\r\n");
      out.write("            text-decoration:none; cursor:pointer; transition:all .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-cancel:hover { border-color:var(--rose); color:#f9a8d4; }\r\n");
      out.write("\r\n");
      out.write("        /* ERROR */\r\n");
      out.write("        .alert-error {\r\n");
      out.write("            background:rgba(244,114,182,.1); border:1px solid rgba(244,114,182,.3);\r\n");
      out.write("            border-radius:10px; padding:.85rem 1rem; margin-bottom:1.4rem;\r\n");
      out.write("            color:#f9a8d4; font-size:.82rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media(max-width:900px) {\r\n");
      out.write("            .sidebar { display:none; } .main { margin-left:0; padding:1.5rem 1rem 3rem; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"orb orb-1\"></div>\r\n");
      out.write("<div class=\"orb orb-2\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- SIDEBAR -->\r\n");
      out.write("<aside class=\"sidebar\">\r\n");
      out.write("    <div class=\"s-logo\">\r\n");
      out.write("        <div class=\"mark\">GameVerse<br>Academy</div>\r\n");
      out.write("        <div class=\"sub\">Admin Panel</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"nav-sec\">\r\n");
      out.write("        <div class=\"nav-lbl\">Navigation</div>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home.jsp\" class=\"nav-a\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"/><polyline points=\"9 22 9 12 15 12 15 22\"/></svg>Accueil\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/mods\" class=\"nav-a active\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z\"/></svg>Mods\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/utilisateurs.jsp\" class=\"nav-a\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/></svg>Utilisateurs\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"nav-lbl\" style=\"margin-top:1rem\">Compte</div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"s-foot\">\r\n");
      out.write("        <div class=\"u-chip\">\r\n");
      out.write("            <div class=\"u-av\">\r\n");
      out.write("                ");
 String su = (String) session.getAttribute("email");
                   String av = (su != null && su.length() >= 2) ? su.substring(0,2).toUpperCase() : "?"; 
      out.write("\r\n");
      out.write("                ");
      out.print( av );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"u-name\">");
      out.print( su != null ? su : "Visiteur" );
      out.write("</div>\r\n");
      out.write("                <div class=\"u-role\">Super Admin</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutController\" method=\"post\">\r\n");
      out.write("            <button type=\"submit\" class=\"logout-btn\">\r\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" style=\"width:13px;height:13px;\">\r\n");
      out.write("                    <path d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\"/>\r\n");
      out.write("                    <polyline points=\"16 17 21 12 16 7\"/>\r\n");
      out.write("                    <line x1=\"21\" y1=\"12\" x2=\"9\" y2=\"12\"/>\r\n");
      out.write("                </svg>\r\n");
      out.write("                Déconnexion\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<!-- MAIN -->\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"ph\">\r\n");
      out.write("        <div class=\"ey\">GameVerse Academy</div>\r\n");
      out.write("        <h1>Modifier le Mod</h1>\r\n");
      out.write("        <p class=\"sub2\">Mise à jour des informations du mod</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-card\">\r\n");
      out.write("\r\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"alert-error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"id-row\">\r\n");
      out.write("            <span class=\"id-label\">ID du mod</span>\r\n");
      out.write("            <span class=\"id-badge\">#");
      out.print( String.format("%02d", mod.getId()) );
      out.write("</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/updateMod\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( mod.getId() );
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Titre</label>\r\n");
      out.write("                <input type=\"text\" name=\"title\" value=\"");
      out.print( mod.getTitle() != null ? mod.getTitle() : "" );
      out.write("\" required/>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Catégorie</label>\r\n");
      out.write("                <select name=\"category\">\r\n");
      out.write("                    <option value=\"\">— Choisir —</option>\r\n");
      out.write("                    <option value=\"Gameplay\"  ");
      out.print( "Gameplay".equals(mod.getCategory())  ? "selected" : "" );
      out.write(">Gameplay</option>\r\n");
      out.write("                    <option value=\"Graphisme\" ");
      out.print( "Graphisme".equals(mod.getCategory()) ? "selected" : "" );
      out.write(">Graphisme</option>\r\n");
      out.write("                    <option value=\"Contenu\"   ");
      out.print( "Contenu".equals(mod.getCategory())   ? "selected" : "" );
      out.write(">Contenu</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Auteur</label>\r\n");
      out.write("                <input type=\"text\" name=\"author\" value=\"");
      out.print( mod.getAuthor() != null ? mod.getAuthor() : "" );
      out.write("\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Description</label>\r\n");
      out.write("                <textarea name=\"description\">");
      out.print( mod.getDescription() != null ? mod.getDescription() : "" );
      out.write("</textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-actions\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Étape 1 : bouton qui affiche la confirmation -->\r\n");
      out.write("    <button type=\"button\" class=\"btn-save\" onclick=\"document.getElementById('confirm-section').style.display='flex'\">\r\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" style=\"width:14px;height:14px;\">\r\n");
      out.write("            <path d=\"M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z\"/>\r\n");
      out.write("            <polyline points=\"17 21 17 13 7 13 7 21\"/>\r\n");
      out.write("            <polyline points=\"7 3 7 8 15 8\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("        Modifier\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/mods\" class=\"btn-cancel\">\r\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" style=\"width:14px;height:14px;\">\r\n");
      out.write("            <line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\"/>\r\n");
      out.write("            <line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("        Annuler\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Étape 2 : section de confirmation -->\r\n");
      out.write("<div id=\"confirm-section\" style=\"display:none; gap:.75rem; margin-top:1rem; padding:1rem;\r\n");
      out.write("     background:rgba(167,139,250,.06); border:1px solid var(--border); border-radius:10px;\r\n");
      out.write("     align-items:center; justify-content:space-between;\">\r\n");
      out.write("    <span style=\"font-size:.82rem; color:var(--text-mid);\">\r\n");
      out.write("        Confirmer la modification de <strong style=\"color:var(--lav-light);\">");
      out.print( mod.getTitle() );
      out.write("</strong> ?\r\n");
      out.write("    </span>\r\n");
      out.write("    <div style=\"display:flex; gap:.5rem;\">\r\n");
      out.write("        <!-- ✅ Bouton qui soumet vraiment le formulaire -->\r\n");
      out.write("        <button type=\"submit\" class=\"btn-save\" style=\"flex:unset; padding:.5rem 1.2rem;\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" style=\"width:13px;height:13px;\">\r\n");
      out.write("                <polyline points=\"20 6 9 17 4 12\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            Confirmer\r\n");
      out.write("        </button>\r\n");
      out.write("        <button type=\"button\" class=\"btn-cancel\"\r\n");
      out.write("                onclick=\"document.getElementById('confirm-section').style.display='none'\"\r\n");
      out.write("                style=\"padding:.5rem 1.2rem;\">\r\n");
      out.write("            Annuler\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
